SR : 
	g++ sender_sr.cpp -pthread -o SenderSR
	g++ receiver_sr.cpp -o ReceiverSR
GBN : 
	g++ sender_gbn.cpp -pthread -o SenderGBN
	g++ receiver_gbn.cpp -o ReceiverGBN
clean :
	rm -f ReceiverGBN SenderGBN SenderSR ReceiverSR